import { ReactNode } from 'react'
import type { Metadata } from 'next'
import { Sidebar } from './components/Sidebar'
import './globals.css'


export const metadata: Metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
}

export default function RootLayout({ children }: { children: ReactNode }) {
  

  return (
    <html lang="en">
    <body>
      <div>
        <Sidebar />
        <main className="py-10 lg:pl-72">
          <div className="px-4 sm:px-6 lg:px-8">
            {children} 
          </div>
        </main>
      </div>
    </body>
    </html>
  )
}
